# Generated by Django 5.1.2 on 2025-05-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_user_type_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False),
        ),
    ]
