# Generated by Django 5.1.2 on 2025-06-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_google_id_user_is_google_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_google_user',
        ),
    ]
