# Generated by Django 5.1 on 2024-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=False, null=True, upload_to='categories'),
        ),
    ]
