# Generated by Django 5.1.2 on 2024-10-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_alter_story_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
