# Generated by Django 5.1.2 on 2024-10-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_remove_story_image_story_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
