# Generated by Django 5.1.2 on 2025-05-27 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_remove_category_image_category_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='read_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='reaeder',
            field=models.ManyToManyField(blank=True, related_name='reader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='story',
            name='writer',
        ),
        migrations.AddField(
            model_name='story',
            name='writer',
            field=models.ManyToManyField(blank=True, related_name='writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
