# Generated by Django 5.1.2 on 2025-05-27 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_story_read_count_story_reaeder_story_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='reaeder',
        ),
        migrations.RemoveField(
            model_name='story',
            name='writer',
        ),
        migrations.AddField(
            model_name='story',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
