# Generated by Django 5.1.2 on 2025-05-27 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_remove_story_reaeder_remove_story_writer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='reader',
            field=models.ManyToManyField(blank=True, related_name='stories_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
