# Generated by Django 5.1.2 on 2025-06-29 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_story_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='review',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
