# Generated by Django 5.1.2 on 2025-07-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_comment_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='date_posted',
        ),
    ]
