# Generated by Django 5.1.2 on 2025-07-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0017_storyreact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='review',
        ),
    ]
