# Generated by Django 5.1.2 on 2025-07-05 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0018_remove_story_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyreact',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacts', to='stories.story'),
        ),
    ]
