# Generated by Django 5.1.2 on 2025-07-05 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_alter_storyreact_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='reader',
            field=models.ManyToManyField(blank=True, related_name='stories_read', related_query_name='readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
