# Generated by Django 5.1.2 on 2025-07-05 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0020_alter_story_reader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='reader',
            field=models.ManyToManyField(blank=True, related_name='stories_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
