# Generated by Django 5.1.2 on 2025-07-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_alter_story_reader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
