# Generated by Django 5.1.2 on 2025-07-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0025_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReaction',
        ),
    ]
