# Generated by Django 5.1.2 on 2025-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0027_comment_commentreaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
