# Generated by Django 5.1.2 on 2025-07-18 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0029_storyrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storyrating',
            unique_together={('user', 'story')},
        ),
    ]
