# Generated by Django 5.1.2 on 2025-07-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0030_alter_storyrating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storyrating',
            unique_together=set(),
        ),
    ]
